"""initial

Revision ID: b42e8e9a3d69
Revises: 
Create Date: 2026-06-08 01:38:15.388212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42e8e9a3d69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_image', sa.String(length=500), nullable=True),
    sa.Column('target_image', sa.String(length=500), nullable=True),
    sa.Column('result_image', sa.String(length=500), nullable=True),
    sa.Column('restore_enabled', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_records_id'), 'process_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_records_id'), table_name='process_records')
    op.drop_table('process_records')
    # ### end Alembic commands ###
