services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=reface
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reface_net

    redis:
      image: redis:8-alpine
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - reface_net
  # backend:
  #   build:
  #     context: ./reface-backend
  #     dockerfile: Dockerfile
  #   container_name: reface-backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - DATABASE_URL=sqlite:///./reface.db
  #   volumes:
  #     - uploads_data:/app/uploads
  #   depends_on:
  #     - redis
  #   networks:
  #     - reface_net

  # celery-worker:
  #   build:
  #     context: ./reface-backend
  #     dockerfile: Dockerfile
  #   container_name: reface-celery-worker
  #   command: ["uv", "run", "celery", "-A", "celery_app", "worker", "--loglevel=info", "--concurrency=1"]
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - DATABASE_URL=sqlite:///./reface.db
  #   volumes:
  #     - uploads_data:/app/uploads
  #   depends_on:
  #     - redis
  #   networks:
  #     - reface_net

networks:
  reface_net:
    driver: bridge
